/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.76
 * Generated at: 2022-03-02 16:20:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import leeten.*;
import java.sql.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

void NoCatch(javax.servlet.http.HttpServletResponse resp)
{
resp.setHeader("Cache-Control","no-store"); //HTTP 1.1
resp.setHeader("Pragma","no-cache"); //HTTP 1.0
resp.setDateHeader("Expires", -1); //prevents caching at the proxy server
resp.setContentType("text/html;charset=big5");
}

void CheckACL(String SysCurrModuleId,String J_OrgId,leeten.Module SysModule,HttpServletRequest request,javax.servlet.http.HttpServletResponse resp)
{
    if(req("FromAP",request).equals("JFlow_FromQueue") && req("OP",request).equals("AdminDraw"))
    {
       //For FormModule
    }    
    else if(req("FromAP",request).equals("JFlow_FormFolder") && req("OP",request).equals("Check") && !req("FI_RecId",request).equals(""))
    {
        //For FormModule
    }
    else
    {
        try
        {
            boolean CheckhasModuleACL=SysModule.hasModuleACL(SysCurrModuleId,J_OrgId);
            if(!CheckhasModuleACL)
            {               
                resp.sendRedirect("/Modules/JEIPKernel/Stop_ACL.jsp");
                return;
            }
        }catch(Exception e) {}
    }
}    

void setCookie(String Name,String Value,javax.servlet.http.HttpServletResponse resp)
{        
    Cookie ck_rem=new Cookie(Name,Value);
    ck_rem.setMaxAge(365 * 24 * 60 * 60);
    resp.addCookie(ck_rem);
}

String getCookie(String Name,javax.servlet.http.HttpServletRequest requ)
{
    Cookie cookies [] = requ.getCookies ();
    Cookie myCookie = null;
    String value="";
    if (cookies != null)
    {
        for (int i = 0; i < cookies.length; i++) 
        {
            if (cookies[i].getName().equals(Name))
            {
                value = cookies[i].getValue();
                break;
            }
        }
    }
    return value;
}        

boolean isPost(javax.servlet.http.HttpServletRequest requ)
{
    if(requ.getMethod().toString().equals("GET"))
        return false;
    else
        return true;
}

String req(String Name,HttpServletRequest requ)
{
    if(requ.getParameter(Name)==null)
    {
        return "";
    }
    else
    {
        return requ.getParameter(Name);
    }
}

String getSession(String Name,javax.servlet.http.HttpSession Seesi)
{
    if(Seesi.getAttribute(Name)==null)
    {
        return "";
    }
    else
    {
        return (String)Seesi.getAttribute(Name);
    }
}

String getApplication(String Name,javax.servlet.ServletContext application)
{
    if(application.getAttribute(Name)==null)
    {
        return "";
    }
    else
    {
        return (String)application.getAttribute(Name);
    }
}

void closeConn(leeten.DataBean Data,Connection Conn) throws Exception
{
    Conn.close();Conn=null;
    Data=null;
}


public void application_init(leeten.Core Core) throws Exception
{    
    if(Core.getApplication("Portalcellpadding").equals(""))
    {
        String Portalcellpadding=Core.getSysVar("Portalcellpadding");
        Core.setApplication("Portalcellpadding",(Portalcellpadding.equals("")?"1":Portalcellpadding));    
    }   
    
    if(Core.getApplication("PortalMenuDelayTime").equals(""))
    {
        String PortalMenuDelayTime=Core.getSysVar("PortalMenuDelayTime");
        Core.setApplication("PortalMenuDelayTime",(PortalMenuDelayTime.equals("")?"1000":PortalMenuDelayTime));    
    }   
    
    if(Core.getApplication("Portal_ShowDeptID").equals(""))
    {
        String Portal_ShowDeptID=Core.getSysVar("Portal_ShowDeptID");
        Core.setApplication("Portal_ShowDeptID",(Portal_ShowDeptID.equals("")?"0":Portal_ShowDeptID));    
    }        

    if(Core.getApplication("Portal_ShowUserID").equals(""))
    {
        String Portal_ShowUserID=Core.getSysVar("Portal_ShowUserID");
        Core.setApplication("Portal_ShowUserID",(Portal_ShowUserID.equals("")?"0":Portal_ShowUserID));    
    }
    
    if(Core.getApplication("PortalLoginURL").equals(""))
    {
        String PortalLoginURL=Core.getSysVar("PortalLoginURL");
        Core.setApplication("PortalLoginURL",(PortalLoginURL.equals("")?"/Portal.jsp":PortalLoginURL));    
    }
    
    if(Core.getApplication("PortalLogoutURL").equals(""))
    {
        String PortalLogoutURL=Core.getSysVar("PortalLogoutURL");
        Core.setApplication("PortalLogoutURL",(PortalLogoutURL.equals("")?"/index.jsp":PortalLogoutURL));    
    }    
    
    
    if(Core.getApplication("UsePortalSubMenuType").equals(""))
    {
        String UsePortalSubMenuType=Core.getSysVar("UsePortalSubMenuType");
        Core.setApplication("UsePortalSubMenuType",(UsePortalSubMenuType.equals("")?"0":UsePortalSubMenuType));    
    }

    if(Core.getApplication("Portal_UserSubMenuType").equals(""))
    {
        String Portal_UserSubMenuType=Core.getSysVar("Portal_UserSubMenuType");
        Core.setApplication("Portal_UserSubMenuType",(Portal_UserSubMenuType.equals("")?"0":Portal_UserSubMenuType));    
    }
    
    if(Core.getApplication("Portal_JUploadFromFileMgr").equals(""))
    {
        String Portal_JUploadFromFileMgr=Core.getSysVar("Portal_JUploadFromFileMgr");
        Core.setApplication("Portal_JUploadFromFileMgr",(Portal_JUploadFromFileMgr.equals("")?"0":Portal_JUploadFromFileMgr));    
    }
    
    if(Core.getApplication("Portal_EnableDymicSubMenu").equals(""))
    {        
        String Portal_EnableDymicSubMenu=Core.getSysVar("Portal_EnableDymicSubMenu");
        Core.setApplication("Portal_EnableDymicSubMenu",(Portal_EnableDymicSubMenu.equals("")?"0":Portal_EnableDymicSubMenu));    
    } 
    
    if(Core.getApplication("Portal_MenuMapLevel").equals(""))
    {        
        String Portal_MenuMapLevel=Core.getSysVar("Portal_MenuMapLevel");
        Core.setApplication("Portal_MenuMapLevel",(Portal_MenuMapLevel.equals("")?"1":Portal_MenuMapLevel));    
    }
    
    if(Core.getApplication("Portal_JHistoryItem").equals(""))
    {        
        String JHistoryItem=Core.getSysVar("Portal_JHistoryItem");
        Core.setApplication("Portal_JHistoryItem",(JHistoryItem.equals("")?"0":JHistoryItem));    
    }    
    

    if(Core.getApplication("Portal_JHistoryItem").equals("1")) Core.setSession("JHistoryItem","1");
    

    if(Core.getApplication("UsePortalSubMenuType").equals("0"))
    {
        if(Core.getSession("JMenuMapLevel").equals(""))
        {        
            String JMenuMapLevel=Core.getUserVar(Core.getSession("J_OrgId"),"JMenuMapLevel");
            if(JMenuMapLevel.equals("")) Core.setSession("JMenuMapLevel","1");
            else Core.setSession("JMenuMapLevel",JMenuMapLevel);    
        } 
    }
    else
    {
        Core.setSession("JMenuMapLevel",Core.getApplication("Portal_MenuMapLevel"));
    }
    
    //使用Portal設定的動態子選單
    if(Core.getApplication("UsePortalSubMenuType").equals("0"))
    {
        if(Core.getSession("EnableDymicSubMenu").equals(""))
        {        
            String EnableDymicSubMenu=Core.getUserVar(Core.getSession("J_OrgId"),"EnableDymicSubMenu");
            if(EnableDymicSubMenu.equals("")) Core.setSession("EnableDymicSubMenu",(EnableDymicSubMenu.equals("")?"0":EnableDymicSubMenu));
            else Core.setSession("EnableDymicSubMenu",EnableDymicSubMenu);    
        }    
    }   
    else
    {
        Core.setSession("EnableDymicSubMenu",Core.getApplication("Portal_EnableDymicSubMenu")); 
    }   
               
    //如果使用Portal設定的子選單
    if(Core.getApplication("UsePortalSubMenuType").equals("0"))
    {
        if(Core.getSession("UserSubMenuType").equals(""))
        {
            String UserSubMenuType=Core.getUserVar(Core.getSession("J_OrgId"),"UserSubMenuType");
            Core.setSession("UserSubMenuType",(UserSubMenuType.equals("")?"0":UserSubMenuType));    
        }
    }
    else
    {
        Core.setSession("UserSubMenuType",Core.getApplication("Portal_UserSubMenuType"));
    }
    
    if(Core.getApplication("Portal_JUploadFromFileMgr").equals("1"))
        Core.setSession("JUploadFromFileMgr",Core.getApplication("Portal_JUploadFromFileMgr"));
    else
    {
        if(Core.getSession("JUploadFromFileMgr").equals(""))
        {
            String JUploadFromFileMgr=Core.getUserVar(Core.getSession("J_OrgId"),"JUploadFromFileMgr");
            Core.setSession("JUploadFromFileMgr",(JUploadFromFileMgr.equals("")?"0":JUploadFromFileMgr));    
        }        
    }
    Core.setSession("PortalUserFirestLogin","1");
}
public void logout_init(leeten.Core Core) throws Exception
{   
    Core.setSession("EnableDymicSubMenu",""); 
    Core.setSession("UserSubMenuType",""); 
    Core.setSession("JUploadFromFileMgr",""); 
    Core.setSession("PortalUserFirestLogin","");
}
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/Modules/JEIPKernel/Util_IO.jsp", Long.valueOf(1646142051614L));
    _jspx_dependants.put("/Modules/JEIPKernel/index_init.jsp", Long.valueOf(1646142051630L));
    _jspx_dependants.put("/Modules/JEIPKernel/Util_Data.jsp", Long.valueOf(1646142051614L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("leeten");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=MS950");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 204800, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

String Portal_Encode=application.getInitParameter("Portal_Encode");request.setCharacterEncoding(Portal_Encode);response.setContentType("text/html; charset=big5");

Connection Conn=null;
leeten.DataBean Data=new leeten.DataBean(pageContext);
Conn=Data.makeConnection();

response.setContentType("text/html; charset=big5");
ResultSet Rs=null;
String Separator=java.io.File.separator; 
String SysRootPath=application.getRealPath("/");
leeten.Date JDate=new leeten.Date();
leeten.ACL ACL=new leeten.ACL(pageContext,Data,Conn);
leeten.Core SysCore=new leeten.Core(pageContext,Data,Conn);
String PortalModifyPWD="",PortalForgetPWD="";
String ErrMsg="";
String J_OrgId="",WantToLogin="";
boolean MultiLogin=false;
String LoginType="",SqlStr="",ID="",PWD="",LoginCount="0",ModuleId="",Verify="",ImageKey="";
String OP=req("OP",request);
ID=req("ID",request);
PWD=req("PWD",request);
ModuleId=req("ModuleId",request);
WantToLogin=req("WantToLogin",request);
Verify=req("Verify",request);

ACL.SystemInit();
String Portal_LoginType=SysCore.getSysVar("Portal_LoginType");
String PortalImageKey=SysCore.getApplication("PortalImageKey");
if(PortalImageKey.equals("")) {PortalImageKey=SysCore.getSysVar("PortalImageKey");SysCore.setApplication("PortalImageKey",PortalImageKey);}

String PortalImageKey_ViewType=SysCore.getApplication("PortalImageKey_ViewType");
if(PortalImageKey_ViewType.equals("")) {PortalImageKey_ViewType=SysCore.getSysVar("PortalImageKey_ViewType");SysCore.setApplication("PortalImageKey_ViewType",PortalImageKey_ViewType);}       

if(Portal_LoginType.indexOf("0")>-1 && Portal_LoginType.indexOf("1")>-1) MultiLogin=true; //進入多重登入畫面
else WantToLogin="1";  //進入登入畫面

String PasswordCount=SysCore.getSysVar("PasswordCount"); //密碼登入限制次數
if(PasswordCount.equals("")) PasswordCount="0";  // 0表不限制
int ErrNum=0;

if(isPost(request) && Verify.equals("1"))
{    
    ErrNum=ACL.CheckUser();    
    
    if(ErrNum==0)
    {
        J_OrgId=session.getAttribute("J_OrgId").toString();            
        SysCore.setUserVar(J_OrgId,"LastLoginTime",JDate.Now());
        if(!SysCore.getApplication("ChangePasswordDays").equals("0"))
        {            
            String LastChangeDate=SysCore.getUserVar(J_OrgId,"Portal_LastChangePWD");            
            if(LastChangeDate.equals(""))
            {       
                LastChangeDate=JDate.Now();
                SysCore.setUserVar(J_OrgId,"Portal_LastChangePWD",LastChangeDate);
            }                       
            if(JDate.DateSub(LastChangeDate,JDate.Now())>=Integer.parseInt(SysCore.getApplication("ChangePasswordDays")))
            {
                SysCore=null;ACL=null;closeConn(Data,Conn);
                response.sendRedirect("index.jsp?OP=CP");
                return;
            }
        }
        application_init(SysCore);
        String MenuDefaultItem=SysCore.getUserVar(J_OrgId,"MenuDefaultItem");
        if(SysCore.getApplication("Portal_ShowAlertDoc").equals("1"))
        {
            out.clear();
            out.println("<html><head><META HTTP-EQUIV='expires' CONTENT='0'><META HTTP-EQUIV='pragma' CONTENT='no-cache'><meta http-equiv='Content-Type' content='text/html; charset=MS950'></head><body><script language=javascript>if(confirm('"+SysCore.getApplication("Portal_AlertDoc").replaceAll("\n","").replaceAll("\r","\\\\n")+"')) document.location.href='"+SysCore.getApplication("PortalLoginURL")+"?"+(ModuleId.equals("")?"Tab="+MenuDefaultItem:"ModuleId="+ModuleId)+"'; else document.location.href='/index.jsp';</script></body></html>");            
            return;    
        }
        else
        {
            out.clear();
            out.println("<html><head><META HTTP-EQUIV='expires' CONTENT='0'><META HTTP-EQUIV='pragma' CONTENT='no-cache'><meta http-equiv='Content-Type' content='text/html; charset=MS950'></head><body><script language=javascript>document.location.href='"+SysCore.getApplication("PortalLoginURL")+"?"+(ModuleId.equals("")?"Tab="+MenuDefaultItem:"ModuleId="+ModuleId)+"';</script></body></html>");
            //response.sendRedirect("Portal.jsp?"+(ModuleId.equals("")?"Tab="+MenuDefaultItem:"ModuleId="+ModuleId));            
            return;            
        }
    }
    else if(ErrNum==5) //帳號已被鎖住,之前就輸入錯了
    {         
        SysCore=null;ACL=null;closeConn(Data,Conn);

      out.write("\r\n");
      out.write("            ");
      if (true) {
        _jspx_page_context.forward("/Modules/JEIPKernel/Stop_LoginCount.jsp");
        return;
      }
      out.write('\r');
      out.write('\n');
          return;
    }  
        
    if(!PasswordCount.equals("0") && ErrNum==1)
    {
        LoginCount=getSession("LoginCount",session);        
        if(LoginCount.equals("")) LoginCount="1";
        else LoginCount=String.valueOf(Integer.parseInt(LoginCount)+1);
        session.setAttribute("LoginCount",LoginCount);
        
        if(LoginCount.equals(PasswordCount)) //如果達到輸入限制的次數,則鎖住使用者,並發Mail通知管理者
        {
            ACL.LockUser(ID);
            //發Mail通知管理者            
            HttpCore HttpCore=new leeten.HttpCore(pageContext,Data,Conn);
            leeten.FileManager FileMgr=new leeten.FileManager();
            String To="",From="",ToName="";        
            From=SysCore.getSysVar("PortalAdminEMail");
            SqlStr="select OrgName,EMail from Org where OrgId in ("+ACL.getSystemAdmin()+")";        
            Rs=Data.getSmt(Conn,SqlStr);
            while(Rs.next())
            {            
                ToName+=Rs.getString("OrgName")+"<br>";
                To+=Rs.getString("EMail")+"##";        
            }
            Rs.close();Rs=null;
           // System.out.println(From+":"+To);
            String PortalTitle=SysCore.getApplication("PortalTitle");    
            String MailContent=FileMgr.ReadFile(SysRootPath+"Modules"+Separator+"JEIPKernel"+Separator+"Mail.txt","big5");    
            MailContent=Data.Replace(MailContent,"{PortalTitle}",PortalTitle);    
            MailContent=Data.Replace(MailContent,"{Subject}",PortalTitle+"-使用者密碼登入錯誤被鎖住");            
            MailContent=Data.Replace(MailContent,"{Body}","<table><tr><td valign=top><font color=#0000ff>使用者帳號:</font></td><td>"+ID+"</td></tr><tr><td><font color=#0000ff>時間:</font></td><td>"+JDate.Now()+"</td></tr><tr><td colspan=2 ><br><br></td></tr></table>");
            HttpCore.SendMail(From,To,PortalTitle+"-系統訊息",MailContent);             
            HttpCore=null;SysCore=null;ACL=null;
            closeConn(Data,Conn);                    

      out.write("\r\n");
      out.write("            ");
      if (true) {
        _jspx_page_context.forward("/Modules/JEIPKernel/Stop_LoginCount.jsp");
        return;
      }
      out.write('\r');
      out.write('\n');
          return;
        }
        else
        {
            ErrMsg="您的密碼登入錯誤 "+LoginCount+" 次,剩下 "+(Integer.parseInt(PasswordCount)-Integer.parseInt(LoginCount))+" 次機會!";
        }
    }
    
    if(ErrNum==6)
    {
        ErrMsg="您輸入的圖片驗證碼錯誤!請重新輸入!";
    }
}
else
{
    session.setAttribute("LoginCount","0");    
}
NoCatch(response);
Html UI=new Html(pageContext,Data,Conn);
UI.Start();

PortalForgetPWD=SysCore.getSysVar("PortalForgetPWD");
PortalModifyPWD=SysCore.getSysVar("PortalModifyPWD");
String Portal_LoginDoc=SysCore.getSysVar("Portal_LoginDoc");
String TemplateId=SysCore.getSysVar("Template").toLowerCase();

if(WantToLogin.equals("1") || !MultiLogin)
{       
    LoginType=req("LoginType",request);
    if(LoginType.equals(""))
    {
        if(Portal_LoginType.equals("")) LoginType="0";
        else
        {
            if(Portal_LoginType.indexOf("0")>-1) LoginType="0";
            if(Portal_LoginType.indexOf("1")>-1) LoginType="1";    
        }
    }             

      out.write("\r\n");
      out.write("<table border=0 cellpadding=0 cellspacing=0 width=\"100%\" height=\"100%\">\r\n");
      out.write("<script Language=\"JavaScript\">\r\n");
      out.write("function CheckData(Frm)\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("        if( Frm.ID.value=='' )\r\n");
      out.write("        {\r\n");
      out.write("            alert(\"請輸入登入帳號!\");       \r\n");
      out.write("            Frm.ID.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        if( Frm.PWD.value=='' )\r\n");
      out.write("        {\r\n");
      out.write("            alert(\"請輸入登入密碼!\");       \r\n");
      out.write("            Frm.PWD.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("       	\r\n");
      out.write("	return true;\r\n");
      out.write("}\r\n");
      out.write("if (top!=self) top.location.href=self.location.href;\r\n");
      out.write("</script>\r\n");
      out.write("<form name='FrmLogin' method=\"POST\" action=\"index.jsp\" onsubmit=\"return CheckData(this)\" autocomplete=\"off\">\r\n");
      out.write("<input type=\"hidden\" name=\"ModuleId\" value=\"");
      out.print(ModuleId);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"WantToLogin\" value=\"1\">\r\n");
      out.write("<input type=\"hidden\" name=\"LoginType\" value=\"");
      out.print(LoginType);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"Verify\" value=\"1\">\r\n");
      out.write("<tr><td  align=center width='100%' height='100%' >\r\n");
      out.write("<table width=\"535\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" height=\"239\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td valign=top background=\"/Template/");
      out.print(TemplateId);
      out.write("/img/login.gif\" align=\"right\">\r\n");
      out.write("        <br><br><br>\r\n");
      out.write("      <div align=\"right\">\r\n");
      out.write("<table width=\"55%\" border=\"0\" cellspacing=\"0\" cellpadding=\"2\">\r\n");
      out.write("          <tr >\r\n");
      out.write("            <td width=\"43%\" valign=\"middle\" class=TBaseFontColor>\r\n");
      out.write("              <div align=\"right\">使用者名稱:</div>\r\n");
      out.write("            </td>\r\n");
      out.write("            <td width=\"57%\" valign=\"middle\">\r\n");
      out.write("              <input type=\"text\" name=\"ID\" size=\"15\" onfocus=\"this.select()\" onclick=\"this.select()\" value=\"");
      out.print(ID);
      out.write("\" MaxLength=\"50\">\r\n");
      out.write("            </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr >\r\n");
      out.write("            <td width=\"43%\" valign=\"middle\" class=TBaseFontColor>\r\n");
      out.write("              <div align=\"right\">密碼:</div>\r\n");
      out.write("            </td>\r\n");
      out.write("            <td valign=\"middle\">\r\n");
      out.write("              <input type=\"password\" name=\"PWD\" size=\"15\" onfocus=\"this.select()\" onclick=\"this.select()\" value=\"");
      out.print(PWD);
      out.write("\" MaxLength=\"20\">\r\n");
      out.write("            </td>\r\n");
      out.write("          </tr>              \r\n");

if(PortalImageKey.equals("1"))    
{    

      out.write("          \r\n");
      out.write("        <tr >\r\n");
      out.write("            <td width=\"43%\" valign=\"middle\" class=TBaseFontColor>\r\n");
      out.write("              <div align=\"right\">圖片驗證碼:</div>\r\n");
      out.write("            </td>\r\n");
      out.write("            <td valign=\"middle\" width=\"57%\">\r\n");
      out.write("                <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" >\r\n");
      out.write("                    <tr><td  style='width:42px'><input type=\"");
      out.print((PortalImageKey_ViewType.equals("1")?"text":"password"));
      out.write("\" name=\"ImageKey\" style='width:40px' onfocus=\"this.select()\" onclick=\"this.select()\" value=\"");
      out.print(ImageKey);
      out.write("\" MaxLength=\"10\"></td>\r\n");
      out.write("                    <td ><img src='/Modules/JEIPKernel/RandomPic.jsp?T=");
      out.print(System.currentTimeMillis());
      out.write("'></td></tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>              \r\n");

}

      out.write("\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td width=\"43%\">&nbsp;</td>\r\n");
      out.write("            <td width=\"57%\">\r\n");
      out.write("              <input  type=\"submit\" name=\"Submit\" value=\"登入\">             \r\n");
      out.write("            </td>\r\n");
      out.write("          </tr>\r\n");
if(LoginType.equals("0")){
      out.write("          \r\n");
      out.write("          <tr >\r\n");
      out.write("            <td width=\"43%\">&nbsp;</td>\r\n");
      out.write("            <td width=\"57%\">\r\n");
      out.write("            ");
if(PortalForgetPWD.equals("1")){
      out.write("<a href=\"javascript:void(0)\" onclick=\"popDialog('ForgetPwd','/Modules/JEIPKernel/ForgetPwd.jsp',400,184);\"> | 忘記密碼 | </a>");
}
      out.write("\r\n");
      out.write("            ");
if(PortalModifyPWD.equals("1")){
      out.write("&nbsp;<a href=\"javascript:void(0)\" onclick=\"popDialog('ModifyPwd','/Modules/JEIPKernel/ModifyPwd.jsp',400,242);\"> | 修改密碼 | </a>");
}
      out.write("</td>\r\n");
      out.write("          </tr>\r\n");
}
      out.write("          \r\n");
      out.write("          <tr >\r\n");
      out.write("            <td width=\"43%\">&nbsp;</td>\r\n");
      out.write("            <td width=\"57%\"><font color=#ff0000>\r\n");
      out.write("            ");
            
            switch(ErrNum)
            {
                case 1:
                    out.println("密碼錯誤!!");
                    break;
                case 2:
                    out.println("查無此帳號!!");
                    break;
            }
            out.println(ErrMsg);
            
      out.write("</font>\r\n");
      out.write("            </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("      </div>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("<center>\r\n");
      out.print(Portal_LoginDoc.replaceAll("\n","<br>"));
      out.write("\r\n");
      out.write("</td></tr></table>\r\n");
      out.write("</form>\r\n");

}   
else
{

      out.write("    \r\n");
      out.write("<table border=0 cellpadding=0 cellspacing=0 width=\"100%\" height=\"100%\">\r\n");
      out.write("<script>    \r\n");
      out.write("if (top!=self) top.location.href=self.location.href;\r\n");
      out.write("</script>\r\n");
      out.write("<form name='FrmLogin'autocomplete=\"off\" method='post'>\r\n");
      out.write("<input type=\"hidden\" name=\"ModuleId\" value=\"");
      out.print(ModuleId);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"WantToLogin\" value=\"1\">\r\n");
      out.write("\r\n");
      out.write("<tr><td valign=middle align=center width='100%' height='100%' >\r\n");
      out.write("<table width=\"535\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" valign=\"middle\" height=\"239\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td valign=\"middle\" background=\"/Template/");
      out.print(TemplateId);
      out.write("/img/login.gif\" align=\"right\">\r\n");
      out.write("      <div align=\"right\"> \r\n");
      out.write("       <table width=\"200\" border=\"0\" cellspacing=\"0\" cellpadding=\"2\">\r\n");
      out.write("          <tr >\r\n");
      out.write("            <td  valign=\"middle\" class=BaseFontColor>\r\n");
      out.write("              <input type=radio name='LoginType' value='0' onclick='FrmLogin.submit()'>一般登入(資料庫驗證)\r\n");
      out.write("            </td>            \r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr >\r\n");
      out.write("            <td  valign=\"middle\" class=BaseFontColor>\r\n");
      out.write("              <input type=radio name='LoginType' value='1' onclick='FrmLogin.submit()'>LDAP登入(AD驗證...)\r\n");
      out.write("            </td>            \r\n");
      out.write("          </tr>                            \r\n");
      out.write("        </table>\r\n");
      out.write("      </div>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("<center>\r\n");
      out.print(Portal_LoginDoc.replaceAll("\n","<br>"));
      out.write("\r\n");
      out.write("</td></tr></table>\r\n");
      out.write("</form>\r\n");
    
}    
if(OP.equals("CP"))
{
    out.println("<script language='javascript'>popDialog('ModifyPwd','/Modules/JEIPKernel/ModifyPwd.jsp?OP=System',400,242);</script>");
}    
UI.End();
UI=null;
ACL=null;SysCore=null;
closeConn(Data,Conn);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("/*    var MinuteTime=60;    \r\n");
      out.write("    var RefreshTime=1*MinuteTime;  \r\n");
      out.write("    var timerid;\r\n");
      out.write("    function ReloadMain() \r\n");
      out.write("    {        \r\n");
      out.write("        RefreshTime--;\r\n");
      out.write("        if (RefreshTime<=0)\r\n");
      out.write("        {\r\n");
      out.write("            window.clearInterval(timerid);            \r\n");
      out.write("            top.location.href=\"/index.jsp\";\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    timerid = window.setInterval(\"ReloadMain()\",1000);*/\r\n");
      out.write("</script>\r\n");
      out.write("<script language=\"javascript\">document.FrmLogin.ID.focus();</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
